server:
  port: 6793

spring:
  application:
    name: ribbon

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6789/eureka/
  instance:
    ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

client-one:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    # 负载均衡策略，RandomRule随机策略，RoundRobinRule轮询策略等等
